### ISSUE TITLE
Test current CDK code with newgs test server

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#32]
To ensure S3/dropbox etc parts already work

**Comment by madisonkeene** [comment]
Hitting an issue re: configuration URLs when talking to genomespace.org - need to email Broad about this

Exception in thread "main" org.genomespace.client.exceptions.ConfigurationError: There was a problem accessing the configuration properties
    at org.genomespace.client.ConfigurationUrls.init(ConfigurationUrls.java:111)
    at CDKExample.main(CDKExample.java:14)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: javax.ws.rs.ProcessingException: javax.ws.rs.core.Response$Status$Family.familyOf(I)Ljavax/ws/rs/core/Response$Status$Family;
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:236)
    at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:671)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:422)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:667)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:396)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:296)
    at org.genomespace.client.ConfigurationUrls.remotePropertiesFile(ConfigurationUrls.java:170)
    at org.genomespace.client.ConfigurationUrls.init(ConfigurationUrls.java:107)
    ... 6 more
Caused by: java.lang.NoSuchMethodError: javax.ws.rs.core.Response$Status$Family.familyOf(I)Ljavax/ws/rs/core/Response$Status$Family;
    at org.glassfish.jersey.message.internal.Statuses$StatusImpl.<init>(Statuses.java:63)
    at org.glassfish.jersey.message.internal.Statuses$StatusImpl.<init>(Statuses.java:54)
    at org.glassfish.jersey.message.internal.Statuses.from(Statuses.java:93)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:507)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:227)
    ... 16 more

**Comment by madisonkeene** [comment]
Above issue now solved - classpath issue. Build with `ant` then run with `java -cp "classes:lib/*"  CDKExample`

**Comment by madisonkeene** [comment]
### Things to test:

General (data-type independent) tests:
- [x] Get username (Session.getCachedUsernameForSSO();).
- [ ] List Home directory.

Data types to test:
- [x] Swift.
- [x] S3.
- [x] Dropbox.
- [ ] Google Drive.

For each data type, test the following:
- [ ] List container.
- [ ] List subdirectory.
- [ ] Get metadata for directory (dmc.getMetadata(dirPath);).
- [ ] Get metadata for file (dmc.getMetadata(dirPath);).
- [ ] Make directory (dmc.createDirectory(baseDirPath, dirName);).
- [ ] Upload small file (dmc.uploadFile(file, dir, name, notify);).
- [ ] Upload large file (dmc.uploadFile(file, dir, name, notify);).
- [ ] Delete file (delete(dmc, dmc.getMetadata(path));).
- [ ] Download file (dmc.downloadFile(fileInfo, file, overwrite);).
- [ ] Get ACLs (fileMetadata.getEffectiveAcl().getAccessControlEntries();).
- [ ] Get READ permission status on ACL (Permission.READ.equals(acle.getPermission())).
- [ ] Get READ permission status on ACL (Permission.WRITE.equals(acle.getPermission())).

**Comment by madisonkeene** [comment]
I wrote a (okay-ish) test script that lives here: https://github.com/madiflannery/genomespace_cdk_test
