### ISSUE TITLE
SimpleFileUpload not working for swift

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#36]
Perhaps not  implemented?

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeToString([B)Ljava/lang/String;
    at org.genomespace.client.DataManagerClientImpl.simpleFileUpload(DataManagerClientImpl.java:669)
    at org.genomespace.client.DataManagerClientImpl.uploadFile(DataManagerClientImpl.java:341)
    at org.genomespace.client.DataManagerClientImpl.uploadFile(DataManagerClientImpl.java:336)
    at CDKExample.uploadFile(CDKExample.java:88)
    at CDKExample.main(CDKExample.java:71)
```

**Comment by madisonkeene** [comment]
this was a general error to do with apache commons - had to rename jar file so it gets imported before  httpclient
