### ISSUE TITLE
Intermittent upload failures from MF portal.

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#57]
``````
           23-Sep-2016 13:51:52.896 [33.284 sec(s) ago]: service: null :auth < :token  "******" > :directory  "/Home/swift:VLSCI-GENOMESPACE/neil2" :expr  "replace(if-null(xpath(daris:pssd-filename/original),if-null(xpath(daris:pssd-object/name),if-null(xpath(asset/name),xpath(asset/id)))),'/','_')" :id  "30366830"
 called by: 23-Sep-2016 13:51:52.650 [33.531 sec(s) ago]: service: null :where  "((xpath(omics:dataset/filetype) = 'fasta') or (xpath(omics:dataset/filetype) = 'fastq')) and (cid starts with '1128.3.11' and asset has content and model='om.pssd.dataset')" :size  "infinity" :action  "pipe" :pipe-nb-threads  "4" :service -name "omics.gs.asset.upload" < :auth < :token  "tY8s7K/e+cyhojlE0lLiD8yRGFU4uSp7" > :directory  "/Home/swift:VLSCI-GENOMESPACE/neil2" :expr  "replace(if-null(xpath(daris:pssd-filename/original),if-null(xpath(daris:pssd-object/name),if-null(xpath(asset/name),xpath(asset/id)))),'/','_')" :id  "30366830" > :stoponerror  "true" :get-content-status "false" :output-format  "xml"
       at arc.mf.server.Services.a(SourceFile:1615)
       at arc.mf.server.Services.a(SourceFile:1812)
       ... 24 more
Caused by: org.genomespace.client.exceptions.GSClientException: There was a problem uploading the file to S3
       at org.genomespace.client.DataManagerClientImpl.simpleFileUpload(DataManagerClientImpl.java:865)
       at org.genomespace.client.DataManagerClientImpl.swiftMultipartUploadFile(DataManagerClientImpl.java:453)
       at org.genomespace.client.DataManagerClientImpl.uploadFile(DataManagerClientImpl.java:372)
       at omics.genomespace.client.GenomeSpaceClient.uploadFile(GenomeSpaceClient.java:187)
       at omics.mf.plugin.services.SvcGenomeSpaceAssetUpload.execute(SvcGenomeSpaceAssetUpload.java:72)
       at omics.mf.plugin.AbstractGenomeSpaceService.execute(AbstractGenomeSpaceService.java:60)
       at arc.mf.modules.plugin.ServiceBridge.a(SourceFile:366)
       at arc.mf.server.Services.a(SourceFile:1676)
       at arc.mf.server.Services.a(SourceFile:1611)
       ... 25 more
Caused by: org.genomespace.client.exceptions.NotFoundException: HTTP 404 Not Found
       at org.genomespace.client.DataManagerClientImpl.wrapException(DataManagerClientImpl.java:1627)
       at org.genomespace.client.DataManagerClientImpl.getMetadata(DataManagerClientImpl.java:1426)
       at org.genomespace.client.DataManagerClientImpl.simpleFileUpload(DataManagerClientImpl.java:861)
       ... 33 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
       at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:917)
       at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:770)
       at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:90)
       at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:671)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
       at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:422)
       at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:667)
       at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:396)
       at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:296)
       at org.genomespace.client.DataManagerClientImpl.getMetadata(DataManagerClientImpl.java:1423)
       ... 34 more
    ```
``````

**Comment by madisonkeene** [comment]
Likely this is a swift issue. Neil/Wilson investigating.

**Comment by madisonkeene** [comment]
This is a NeCTAR swift issue, not a GS issue. Closing.
